#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Sep 23 02:06:32 EEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=6
shaderPack=Solas Shader V3.3.zip
